# Generated by Django 6.0.4 on 2026-05-18 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('required_streak', models.IntegerField(help_text='Требуемая серия дней (7, 30, 100)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/')),
            ],
        ),
        migrations.AlterField(
            model_name='focussession',
            name='plan_done',
            field=models.BooleanField(default=False, verbose_name='План выполнен'),
        ),
        migrations.AlterField(
            model_name='focussession',
            name='plan_text',
            field=models.TextField(blank=True, verbose_name='План на сессию'),
        ),
        migrations.AlterField(
            model_name='workspaceconfig',
            name='theme',
            field=models.CharField(choices=[('dark', 'Тёмная'), ('light', 'Светлая'), ('forest', 'Лесная')], default='light', max_length=20),
        ),
        migrations.CreateModel(
            name='EarnedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
