# Generated by Django 6.0.4 on 2026-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement_alter_focussession_plan_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_focus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
