# Generated by Django 6.0.4 on 2026-05-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_last_focus_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['order', 'required_streak']},
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, help_text='Описание достижения'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_friends',
            field=models.IntegerField(blank=True, help_text='Требуемое количество друзей', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_hours',
            field=models.FloatField(blank=True, help_text='Требуемое количество часов', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_pdfs_read',
            field=models.IntegerField(blank=True, help_text='Прочитанных PDF', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_sessions',
            field=models.IntegerField(blank=True, help_text='Требуемое количество сессий', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='required_videos_watched',
            field=models.IntegerField(blank=True, help_text='Просмотренных видео', null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('streak', 'Стрик'), ('friends', 'Друзья'), ('sessions', 'Сессии'), ('hours', 'Часы фокуса'), ('media', 'Медиа'), ('special', 'Особые')], default='streak', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='total_pdfs_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_videos_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='required_streak',
            field=models.IntegerField(blank=True, help_text='Требуемая серия дней', null=True),
        ),
    ]
