# Generated by Django 6.0.4 on 2026-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceconfig',
            name='focus_mode',
            field=models.CharField(choices=[('timer_only', 'Только таймер'), ('timer_pdf', 'Таймер + PDF'), ('timer_youtube', 'Таймер + YouTube')], default='timer_only', max_length=20),
        ),
    ]
