# Generated by Django 6.0.4 on 2026-06-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workspaceconfig_focus_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceconfig',
            name='pdf_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspaceconfig',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='workspaceconfig',
            name='video_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspaceconfig',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube ссылка'),
        ),
    ]
